# Generated by Django 3.0.4 on 2020-03-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddetail',
            name='example',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
